%% Step 14: Final refinement validation and project summary
clear;
clc;
format long g;

fprintf('====================================================\n');
fprintf('STEP 14 - FINAL REFINEMENT VALIDATION\n');
fprintf('====================================================\n\n');

%% Project settings
a = 0.0;
b = 1.0;

n_inner_refined = 320;
n_outer_refined = 320;

refined_derivative_spacing = 0.0025;
stencil_size = 5;

x_tolerance = 0.5e-9;
maximum_iterations = 100;

six_decimal_tolerance = 0.5e-6;

fprintf('Project interval                : [%.1f, %.1f]\n', a, b);
fprintf('Refined inner Simpson count     : %d\n', n_inner_refined);
fprintf('Refined outer Simpson count     : %d\n', n_outer_refined);
fprintf('Refined derivative spacing      : %.6f\n', ...
    refined_derivative_spacing);
fprintf('Bisection tolerance             : %.10e\n', x_tolerance);
fprintf('Six-decimal comparison tolerance: %.10e\n\n', ...
    six_decimal_tolerance);

%% Determine project folders
script_full_path = mfilename('fullpath');

if isempty(script_full_path)
    error(['The script must be saved before execution so that ', ...
           'the project path can be determined.']);
end

code_directory = fileparts(script_full_path);
project_root = fileparts(code_directory);

results_directory = fullfile(project_root, 'results');

if ~exist(results_directory, 'dir')
    mkdir(results_directory);
end

fprintf('Project root:\n%s\n\n', project_root);

%% File paths for previously computed results
integral_mean_file = fullfile( ...
    results_directory, ...
    'integral_mean_summary.csv' ...
);

integral_point_file = fullfile( ...
    results_directory, ...
    'integral_mean_point_summary.csv' ...
);

derivative_slope_file = fullfile( ...
    results_directory, ...
    'derivative_mean_value_slope_summary.csv' ...
);

derivative_point_file = fullfile( ...
    results_directory, ...
    'derivative_mean_point_summary.csv' ...
);

required_files = { ...
    integral_mean_file, ...
    integral_point_file, ...
    derivative_slope_file, ...
    derivative_point_file ...
};

for file_index = 1:numel(required_files)

    if ~isfile(required_files{file_index})
        error('A required result file was not found:\n%s', ...
            required_files{file_index});
    end
end

fprintf('All previous result files were found: PASSED\n\n');

%% Read the original results
integral_mean_table = readtable(integral_mean_file);
integral_point_table = readtable(integral_point_file);
derivative_slope_table = readtable(derivative_slope_file);
derivative_point_table = readtable(derivative_point_file);

required_integral_mean_variable = 'IntegralMean';
required_integral_point_variable = 'IntegralMeanPoint';
required_derivative_slope_variable = 'AverageSlope';
required_derivative_point_variable = 'DerivativeMeanPoint';

if ~ismember( ...
        required_integral_mean_variable, ...
        integral_mean_table.Properties.VariableNames)

    error('IntegralMean was not found in the Step 06 result file.');
end

if ~ismember( ...
        required_integral_point_variable, ...
        integral_point_table.Properties.VariableNames)

    error('IntegralMeanPoint was not found in the Step 09 file.');
end

if ~ismember( ...
        required_derivative_slope_variable, ...
        derivative_slope_table.Properties.VariableNames)

    error('AverageSlope was not found in the Step 12 file.');
end

if ~ismember( ...
        required_derivative_point_variable, ...
        derivative_point_table.Properties.VariableNames)

    error('DerivativeMeanPoint was not found in the Step 13 file.');
end

original_integral_mean = ...
    integral_mean_table.IntegralMean(1);

original_integral_point = ...
    integral_point_table.IntegralMeanPoint(1);

original_average_slope = ...
    derivative_slope_table.AverageSlope(1);

original_derivative_point = ...
    derivative_point_table.DerivativeMeanPoint(1);

fprintf('Original project results:\n\n');

fprintf('Integral mean M_I = %.15f\n', ...
    original_integral_mean);

fprintf('Integral point c_I = %.15f\n', ...
    original_integral_point);

fprintf('Average slope M_D = %.15f\n', ...
    original_average_slope);

fprintf('Derivative point c_D = %.15f\n\n', ...
    original_derivative_point);

%% Refined integral mean calculation
refined_project_function = @(x) ...
    project_function(x, n_inner_refined);

refined_integral_value = composite_simpson( ...
    refined_project_function, ...
    a, ...
    b, ...
    n_outer_refined ...
);

refined_integral_mean = ...
    refined_integral_value / (b - a);

fprintf('Refined integral calculation completed.\n');

%% Recompute the integral mean theorem point
refined_integral_equation = @(x) ...
    project_function(x, n_inner_refined) ...
    - refined_integral_mean;

[refined_integral_point, ~, ...
 refined_integral_left, refined_integral_right, ...
 refined_integral_iterations] = ...
    bisection_method( ...
        refined_integral_equation, ...
        0.406, ...
        0.407, ...
        x_tolerance, ...
        maximum_iterations ...
    );

refined_integral_residual = abs( ...
    project_function( ...
        refined_integral_point, ...
        n_inner_refined ...
    ) ...
    - refined_integral_mean ...
);

fprintf('Refined integral theorem point completed.\n');

%% Construct the refined derivative grid
refined_subinterval_count = round( ...
    (b - a) / refined_derivative_spacing ...
);

refined_x_nodes = linspace( ...
    a, ...
    b, ...
    refined_subinterval_count + 1 ...
).';

refined_F_nodes = project_function( ...
    refined_x_nodes, ...
    n_inner_refined ...
);

refined_average_slope = ...
    (refined_F_nodes(end) - refined_F_nodes(1)) ...
    / (b - a);

refined_numerical_derivative = @(x) ...
    project_derivative_approximation( ...
        refined_x_nodes, ...
        refined_F_nodes, ...
        x, ...
        stencil_size ...
    );

fprintf('Refined numerical derivative grid completed.\n');

%% Recompute the derivative mean theorem point
refined_derivative_equation = @(x) ...
    refined_numerical_derivative(x) ...
    - refined_average_slope;

[refined_derivative_point, ~, ...
 refined_derivative_left, refined_derivative_right, ...
 refined_derivative_iterations] = ...
    bisection_method( ...
        refined_derivative_equation, ...
        0.5115, ...
        0.5120, ...
        x_tolerance, ...
        maximum_iterations ...
    );

refined_derivative_at_point = ...
    refined_numerical_derivative( ...
        refined_derivative_point ...
    );

refined_derivative_residual = abs( ...
    refined_derivative_at_point ...
    - refined_average_slope ...
);

fprintf('Refined derivative theorem point completed.\n\n');

%% Compare original and refined results
integral_mean_difference = abs( ...
    refined_integral_mean ...
    - original_integral_mean ...
);

integral_point_difference = abs( ...
    refined_integral_point ...
    - original_integral_point ...
);

average_slope_difference = abs( ...
    refined_average_slope ...
    - original_average_slope ...
);

derivative_point_difference = abs( ...
    refined_derivative_point ...
    - original_derivative_point ...
);

quantity_names = [ ...
    "Integral mean M_I"; ...
    "Integral theorem point c_I"; ...
    "Average slope M_D"; ...
    "Derivative theorem point c_D" ...
];

original_values = [ ...
    original_integral_mean; ...
    original_integral_point; ...
    original_average_slope; ...
    original_derivative_point ...
];

refined_values = [ ...
    refined_integral_mean; ...
    refined_integral_point; ...
    refined_average_slope; ...
    refined_derivative_point ...
];

absolute_differences = abs( ...
    refined_values - original_values ...
);

comparison_table = table( ...
    quantity_names, ...
    original_values, ...
    refined_values, ...
    absolute_differences, ...
    'VariableNames', ...
    { ...
        'Quantity', ...
        'OriginalValue', ...
        'RefinedValue', ...
        'AbsoluteDifference' ...
    } ...
);

fprintf('Original-versus-refined comparison:\n\n');
disp(comparison_table);

%% Display refined final results
fprintf('Refined final results:\n\n');

fprintf('Refined integral mean M_I = %.15f\n', ...
    refined_integral_mean);

fprintf('Refined integral point c_I = %.15f\n', ...
    refined_integral_point);

fprintf('Rounded refined c_I = %.6f\n', ...
    round(refined_integral_point, 6));

fprintf('Integral equation residual = %.15e\n', ...
    refined_integral_residual);

fprintf('Integral bisection iterations = %d\n\n', ...
    refined_integral_iterations);

fprintf('Refined average slope M_D = %.15f\n', ...
    refined_average_slope);

fprintf('Refined derivative point c_D = %.15f\n', ...
    refined_derivative_point);

fprintf('Rounded refined c_D = %.6f\n', ...
    round(refined_derivative_point, 6));

fprintf('Derivative equation residual = %.15e\n', ...
    refined_derivative_residual);

fprintf('Derivative bisection iterations = %d\n\n', ...
    refined_derivative_iterations);

fprintf('Original-refined absolute differences:\n');

fprintf('|Delta M_I| = %.15e\n', ...
    integral_mean_difference);

fprintf('|Delta c_I| = %.15e\n', ...
    integral_point_difference);

fprintf('|Delta M_D| = %.15e\n', ...
    average_slope_difference);

fprintf('|Delta c_D| = %.15e\n\n', ...
    derivative_point_difference);

%% Final accuracy validation
if any(absolute_differences > six_decimal_tolerance)
    error(['At least one original-refined difference exceeds ', ...
           'the six-decimal tolerance.']);
end

fprintf('Refinement-difference accuracy test: PASSED\n');

if round(original_integral_point, 6) ~= ...
        round(refined_integral_point, 6)

    error('The six-decimal value of c_I is not stable.');
end

fprintf('Integral-point rounding stability test: PASSED\n');

if round(original_derivative_point, 6) ~= ...
        round(refined_derivative_point, 6)

    error('The six-decimal value of c_D is not stable.');
end

fprintf('Derivative-point rounding stability test: PASSED\n');

if refined_integral_residual > 1e-8
    error('The refined integral theorem residual is too large.');
end

fprintf('Refined integral theorem test: PASSED\n');

if refined_derivative_residual > 1e-8
    error('The refined derivative theorem residual is too large.');
end

fprintf('Refined derivative theorem test: PASSED\n');

if refined_integral_point <= a || ...
        refined_integral_point >= b || ...
        refined_derivative_point <= a || ...
        refined_derivative_point >= b

    error('At least one final theorem point is outside (0, 1).');
end

fprintf('Final-point interval test: PASSED\n');

%% Save the comparison table
comparison_file_path = fullfile( ...
    results_directory, ...
    'final_project_refinement_comparison.csv' ...
);

writetable(comparison_table, comparison_file_path);

%% Save the consolidated final result table
theorem_names = [ ...
    "Integral mean theorem"; ...
    "Derivative mean value theorem" ...
];

final_points = [ ...
    refined_integral_point; ...
    refined_derivative_point ...
];

rounded_final_points = round(final_points, 6);

target_values = [ ...
    refined_integral_mean; ...
    refined_average_slope ...
];

theorem_residuals = [ ...
    refined_integral_residual; ...
    refined_derivative_residual ...
];

final_result_table = table( ...
    theorem_names, ...
    final_points, ...
    rounded_final_points, ...
    target_values, ...
    theorem_residuals, ...
    'VariableNames', ...
    { ...
        'Theorem', ...
        'ComputedPoint', ...
        'RoundedPointSixDecimals', ...
        'TargetValue', ...
        'Residual' ...
    } ...
);

final_result_file_path = fullfile( ...
    results_directory, ...
    'final_project_results.csv' ...
);

writetable(final_result_table, final_result_file_path);

fprintf('\nFinal consolidated results:\n\n');
disp(final_result_table);

fprintf('Refinement comparison saved to:\n%s\n', ...
    comparison_file_path);

fprintf('\nFinal project results saved to:\n%s\n', ...
    final_result_file_path);

%% Final message
fprintf('\nStep 14 completed successfully.\n');
fprintf('====================================================\n');