%% Step 06: Compute the outer integral and integral mean value
clear;
clc;
format long g;

fprintf('====================================================\n');
fprintf('STEP 06 - OUTER INTEGRAL AND INTEGRAL MEAN\n');
fprintf('====================================================\n\n');

%% Project settings
a = 0.0;
b = 1.0;

decimal_digits = 6;
tolerance = 0.5 * 10^(-decimal_digits);

n_inner_fine = 160;
n_inner_coarse = 80;

outer_subinterval_counts = [20; 40; 80; 160];

fprintf('Project interval          : [%.1f, %.1f]\n', a, b);
fprintf('Fine inner Simpson count  : %d\n', n_inner_fine);
fprintf('Coarse inner Simpson count: %d\n', n_inner_coarse);
fprintf('Target tolerance          : %.10e\n\n', tolerance);

%% Determine project folders
script_full_path = mfilename('fullpath');

if isempty(script_full_path)
    error(['The script must be saved before execution so that ', ...
           'the project path can be determined.']);
end

code_directory = fileparts(script_full_path);
project_root = fileparts(code_directory);

results_directory = fullfile(project_root, 'results');

if ~exist(results_directory, 'dir')
    mkdir(results_directory);
end

fprintf('Project root:\n%s\n\n', project_root);

%% Evaluate the outer integral with progressively finer grids
number_of_outer_grids = numel(outer_subinterval_counts);

outer_integral_values = zeros(number_of_outer_grids, 1);

outer_function_fine = @(x) project_function(x, n_inner_fine);

for k = 1:number_of_outer_grids

    current_outer_n = outer_subinterval_counts(k);

    outer_integral_values(k) = composite_simpson( ...
        outer_function_fine, ...
        a, ...
        b, ...
        current_outer_n ...
    );
end

%% Successive differences and Simpson error estimates
successive_differences = NaN(number_of_outer_grids, 1);
estimated_outer_errors = NaN(number_of_outer_grids, 1);

for k = 2:number_of_outer_grids

    successive_differences(k) = abs( ...
        outer_integral_values(k) ...
        - outer_integral_values(k - 1) ...
    );

    estimated_outer_errors(k) = ...
        successive_differences(k) / 15;
end

%% Estimate the effect of the inner Simpson discretization
n_outer_fine = outer_subinterval_counts(end);

outer_function_coarse = @(x) ...
    project_function(x, n_inner_coarse);

integral_with_coarse_inner_grid = composite_simpson( ...
    outer_function_coarse, ...
    a, ...
    b, ...
    n_outer_fine ...
);

integral_with_fine_inner_grid = outer_integral_values(end);

estimated_inner_error = abs( ...
    integral_with_fine_inner_grid ...
    - integral_with_coarse_inner_grid ...
) / 15;

estimated_outer_error = estimated_outer_errors(end);

estimated_total_error = ...
    estimated_outer_error + estimated_inner_error;

%% Compute the integral mean
interval_length = b - a;

integral_mean_value = ...
    integral_with_fine_inner_grid / interval_length;

estimated_mean_error = ...
    estimated_total_error / interval_length;

%% Construct the convergence table
convergence_table = table( ...
    outer_subinterval_counts, ...
    outer_integral_values, ...
    successive_differences, ...
    estimated_outer_errors, ...
    'VariableNames', ...
    { ...
        'n_outer', ...
        'OuterIntegral', ...
        'SuccessiveDifference', ...
        'EstimatedOuterError' ...
    } ...
);

fprintf('Outer-integral convergence table:\n\n');
disp(convergence_table);

%% Display the final numerical results
fprintf('Final numerical results:\n\n');

fprintf('Integral using inner n = %d and outer n = %d:\n', ...
    n_inner_fine, n_outer_fine);

fprintf('Integral value       = %.15f\n\n', ...
    integral_with_fine_inner_grid);

fprintf('Integral mean value  = %.15f\n\n', ...
    integral_mean_value);

fprintf('Estimated outer error = %.15e\n', ...
    estimated_outer_error);

fprintf('Estimated inner error = %.15e\n', ...
    estimated_inner_error);

fprintf('Estimated total error = %.15e\n', ...
    estimated_total_error);

fprintf('Estimated mean error  = %.15e\n\n', ...
    estimated_mean_error);

%% Accuracy test
if estimated_total_error > tolerance
    error(['The estimated total integration error exceeds ', ...
           'the required six-decimal tolerance.']);
end

fprintf('Six-decimal integration accuracy test: PASSED\n');

%% Verify that the mean value is inside the numerical range of F
verification_grid = linspace(a, b, 101);

F_verification = project_function( ...
    verification_grid, ...
    n_inner_fine ...
);

minimum_F = min(F_verification);
maximum_F = max(F_verification);

fprintf('Numerical range of F on verification grid:\n');
fprintf('Minimum F = %.15f\n', minimum_F);
fprintf('Maximum F = %.15f\n', maximum_F);

if integral_mean_value < minimum_F - tolerance || ...
        integral_mean_value > maximum_F + tolerance

    error(['The integral mean does not lie inside the ', ...
           'numerical range of F.']);
end

fprintf('Integral-mean range test: PASSED\n');

%% Save the convergence table
convergence_file_path = fullfile( ...
    results_directory, ...
    'outer_integral_convergence.csv' ...
);

writetable(convergence_table, convergence_file_path);

%% Save the summary results
summary_table = table( ...
    n_inner_fine, ...
    n_outer_fine, ...
    integral_with_fine_inner_grid, ...
    integral_mean_value, ...
    estimated_outer_error, ...
    estimated_inner_error, ...
    estimated_total_error, ...
    'VariableNames', ...
    { ...
        'n_inner', ...
        'n_outer', ...
        'IntegralValue', ...
        'IntegralMean', ...
        'EstimatedOuterError', ...
        'EstimatedInnerError', ...
        'EstimatedTotalError' ...
    } ...
);

summary_file_path = fullfile( ...
    results_directory, ...
    'integral_mean_summary.csv' ...
);

writetable(summary_table, summary_file_path);

fprintf('\nConvergence table saved to:\n%s\n', ...
    convergence_file_path);

fprintf('\nSummary results saved to:\n%s\n', ...
    summary_file_path);

%% Final message
fprintf('\nStep 06 completed successfully.\n');
fprintf('====================================================\n');