%% Step 11: Compute and validate the numerical derivative of F(x)
clear;
clc;
format long g;

fprintf('====================================================\n');
fprintf('STEP 11 - NUMERICAL DERIVATIVE OF PROJECT FUNCTION\n');
fprintf('====================================================\n\n');

%% Project settings
a = 0.0;
b = 1.0;

n_inner = 160;
stencil_size = 5;

grid_spacings = [0.02; 0.01; 0.005];

target_tolerance = 0.5e-6;

fprintf('Project interval       : [%.1f, %.1f]\n', a, b);
fprintf('Inner Simpson count    : %d\n', n_inner);
fprintf('Local stencil size     : %d\n', stencil_size);
fprintf('Target tolerance       : %.10e\n\n', target_tolerance);

%% Determine project folders
script_full_path = mfilename('fullpath');

if isempty(script_full_path)
    error(['The script must be saved before execution so that ', ...
           'the project path can be determined.']);
end

code_directory = fileparts(script_full_path);
project_root = fileparts(code_directory);

results_directory = fullfile(project_root, 'results');
figures_directory = fullfile(project_root, 'figures');

if ~exist(results_directory, 'dir')
    mkdir(results_directory);
end

if ~exist(figures_directory, 'dir')
    mkdir(figures_directory);
end

fprintf('Project root:\n%s\n\n', project_root);

%% Common points used for convergence comparison
coarse_spacing = grid_spacings(1);

number_of_common_subintervals = round( ...
    (b - a) / coarse_spacing ...
);

x_common = linspace( ...
    a, ...
    b, ...
    number_of_common_subintervals + 1 ...
).';

number_of_grids = numel(grid_spacings);

derivative_common = zeros( ...
    numel(x_common), ...
    number_of_grids ...
);

grid_node_counts = zeros(number_of_grids, 1);

%% Compute derivatives on progressively finer grids
for grid_index = 1:number_of_grids

    current_spacing = grid_spacings(grid_index);

    current_subinterval_count = round( ...
        (b - a) / current_spacing ...
    );

    current_x_grid = linspace( ...
        a, ...
        b, ...
        current_subinterval_count + 1 ...
    ).';

    current_F_grid = project_function( ...
        current_x_grid, ...
        n_inner ...
    );

    [~, current_derivative_common] = ...
        local_newton_interpolant( ...
            current_x_grid, ...
            current_F_grid, ...
            x_common, ...
            stencil_size ...
        );

    derivative_common(:, grid_index) = ...
        current_derivative_common;

    grid_node_counts(grid_index) = numel(current_x_grid);

    fprintf('Grid h = %.6f, nodes = %d: COMPLETED\n', ...
        current_spacing, ...
        numel(current_x_grid));

    %% Preserve the finest grid for the final table and figure
    if grid_index == number_of_grids

        x_fine = current_x_grid;
        F_fine = current_F_grid;

        [interpolated_F_fine, derivative_fine, ...
         stencil_start_fine] = ...
            local_newton_interpolant( ...
                x_fine, ...
                F_fine, ...
                x_fine, ...
                stencil_size ...
            );
    end
end

fprintf('\nAll derivative grids completed successfully.\n\n');

%% Compare successive grid refinements
coarse_to_medium_difference = abs( ...
    derivative_common(:, 2) ...
    - derivative_common(:, 1) ...
);

medium_to_fine_difference = abs( ...
    derivative_common(:, 3) ...
    - derivative_common(:, 2) ...
);

% A five-point local quartic derivative has fourth-order behavior.
estimated_fine_error = ...
    medium_to_fine_difference / 15;

maximum_coarse_to_medium_difference = ...
    max(coarse_to_medium_difference);

maximum_medium_to_fine_difference = ...
    max(medium_to_fine_difference);

maximum_estimated_fine_error = ...
    max(estimated_fine_error);

observed_order = log2( ...
    maximum_coarse_to_medium_difference ...
    / maximum_medium_to_fine_difference ...
);

%% Interpolation consistency test at grid nodes
maximum_node_interpolation_error = max(abs( ...
    interpolated_F_fine - F_fine ...
));

fprintf('Convergence summary:\n\n');

fprintf('Max |D_0.01 - D_0.02| = %.15e\n', ...
    maximum_coarse_to_medium_difference);

fprintf('Max |D_0.005 - D_0.01| = %.15e\n', ...
    maximum_medium_to_fine_difference);

fprintf('Estimated maximum fine-grid error = %.15e\n', ...
    maximum_estimated_fine_error);

fprintf('Observed convergence order = %.10f\n\n', ...
    observed_order);

fprintf('Maximum interpolation error at fine-grid nodes:\n');
fprintf('%.15e\n\n', maximum_node_interpolation_error);

%% Construct the convergence table
convergence_table = table( ...
    x_common, ...
    derivative_common(:, 1), ...
    derivative_common(:, 2), ...
    derivative_common(:, 3), ...
    coarse_to_medium_difference, ...
    medium_to_fine_difference, ...
    estimated_fine_error, ...
    'VariableNames', ...
    { ...
        'x', ...
        'Derivative_h_002', ...
        'Derivative_h_001', ...
        'Derivative_h_0005', ...
        'Difference_002_001', ...
        'Difference_001_0005', ...
        'EstimatedFineError' ...
    } ...
);

%% Display selected values at spacing 0.1
selected_indices = 1:5:numel(x_common);

selected_table = convergence_table( ...
    selected_indices, ...
    {'x', 'Derivative_h_0005', 'EstimatedFineError'} ...
);

fprintf('Selected fine-grid derivative values:\n\n');
disp(selected_table);

%% Validation tests
if maximum_estimated_fine_error > target_tolerance
    error(['The estimated derivative error exceeds ', ...
           'the six-decimal target tolerance.']);
end

fprintf('Derivative accuracy test: PASSED\n');

if observed_order < 3.5
    error('The observed convergence order is lower than expected.');
end

fprintf('Fourth-order convergence test: PASSED\n');

if maximum_node_interpolation_error > 1e-12
    error('The interpolation does not reproduce the grid-node values.');
end

fprintf('Grid-node interpolation test: PASSED\n');

if any(~isfinite(derivative_fine)) || ...
        any(~isreal(derivative_fine))

    error('The final derivative contains invalid values.');
end

fprintf('Finite real derivative test: PASSED\n');

%% Save fine-grid derivative table
fine_derivative_table = table( ...
    x_fine, ...
    F_fine, ...
    derivative_fine, ...
    stencil_start_fine, ...
    'VariableNames', ...
    { ...
        'x', ...
        'F_x', ...
        'NumericalDerivative', ...
        'StencilStartIndex' ...
    } ...
);

fine_table_path = fullfile( ...
    results_directory, ...
    'project_function_numerical_derivative.csv' ...
);

writetable(fine_derivative_table, fine_table_path);

%% Save convergence table
convergence_table_path = fullfile( ...
    results_directory, ...
    'project_derivative_convergence.csv' ...
);

writetable(convergence_table, convergence_table_path);

%% Save convergence summary
summary_table = table( ...
    grid_spacings, ...
    grid_node_counts, ...
    'VariableNames', ...
    {'GridSpacing', 'NumberOfNodes'} ...
);

summary_table_path = fullfile( ...
    results_directory, ...
    'project_derivative_grid_summary.csv' ...
);

writetable(summary_table, summary_table_path);

%% Plot the final numerical derivative
figure_handle = figure('Color', 'w');

plot( ...
    x_fine, ...
    derivative_fine, ...
    'LineWidth', ...
    1.5 ...
);

hold on;

yline(0, '--', 'LineWidth', 1.0);

grid on;

xlabel('x');
ylabel('Numerical approximation of F''(x)');
title('Numerical Derivative of the Project Function');

axes_handle = gca;
axes_handle.Toolbar.Visible = 'off';

figure_file_path = fullfile( ...
    figures_directory, ...
    'project_function_numerical_derivative.png' ...
);

exportgraphics( ...
    figure_handle, ...
    figure_file_path, ...
    'Resolution', ...
    300 ...
);

%% Display saved paths
fprintf('\nFine derivative table saved to:\n%s\n', ...
    fine_table_path);

fprintf('\nConvergence table saved to:\n%s\n', ...
    convergence_table_path);

fprintf('\nGrid summary saved to:\n%s\n', ...
    summary_table_path);

fprintf('\nDerivative figure saved to:\n%s\n', ...
    figure_file_path);

%% Final message
fprintf('\nStep 11 completed successfully.\n');
fprintf('====================================================\n');