%% Step 09: Compute the integral mean theorem point
clear;
clc;
format long g;

fprintf('====================================================\n');
fprintf('STEP 09 - INTEGRAL MEAN THEOREM POINT\n');
fprintf('====================================================\n\n');

%% Project settings
a = 0.0;
b = 1.0;

n_inner = 160;

% A stricter tolerance is used to stabilize six-decimal rounding.
x_tolerance = 0.5e-8;
maximum_iterations = 100;

fprintf('Project interval      : [%.1f, %.1f]\n', a, b);
fprintf('Inner Simpson count   : %d\n', n_inner);
fprintf('Bisection tolerance   : %.10e\n', x_tolerance);
fprintf('Maximum iterations    : %d\n\n', maximum_iterations);

%% Determine project folders
script_full_path = mfilename('fullpath');

if isempty(script_full_path)
    error(['The script must be saved before execution so that ', ...
           'the project path can be determined.']);
end

code_directory = fileparts(script_full_path);
project_root = fileparts(code_directory);

results_directory = fullfile(project_root, 'results');
figures_directory = fullfile(project_root, 'figures');

if ~exist(results_directory, 'dir')
    mkdir(results_directory);
end

if ~exist(figures_directory, 'dir')
    mkdir(figures_directory);
end

fprintf('Project root:\n%s\n\n', project_root);

%% Read the integral mean from Step 06
mean_summary_path = fullfile( ...
    results_directory, ...
    'integral_mean_summary.csv' ...
);

if ~isfile(mean_summary_path)
    error(['The Step 06 integral mean file was not found:\n', ...
           mean_summary_path]);
end

mean_summary_table = readtable(mean_summary_path);

if ~ismember( ...
        'IntegralMean', ...
        mean_summary_table.Properties.VariableNames)

    error('The Step 06 file does not contain IntegralMean.');
end

integral_mean_value = mean_summary_table.IntegralMean(1);

if ~isscalar(integral_mean_value) || ...
        ~isreal(integral_mean_value) || ...
        ~isfinite(integral_mean_value)

    error('The integral mean value is invalid.');
end

fprintf('Integral mean value:\n');
fprintf('M_I = %.15f\n\n', integral_mean_value);

%% Read the sign-change bracket from Step 07
bracket_file_path = fullfile( ...
    results_directory, ...
    'integral_mean_root_brackets.csv' ...
);

if ~isfile(bracket_file_path)
    error(['The Step 07 bracket file was not found:\n', ...
           bracket_file_path]);
end

bracket_table = readtable(bracket_file_path);

required_bracket_variables = {'x_left', 'x_right'};

if ~all(ismember( ...
        required_bracket_variables, ...
        bracket_table.Properties.VariableNames))

    error('The Step 07 file does not contain valid bracket columns.');
end

if height(bracket_table) ~= 1
    error(['Exactly one integral-mean root bracket was expected, ', ...
           'but %d brackets were found.'], ...
           height(bracket_table));
end

initial_left = bracket_table.x_left(1);
initial_right = bracket_table.x_right(1);

fprintf('Initial root bracket:\n');
fprintf('[%.15f, %.15f]\n\n', ...
    initial_left, initial_right);

%% Define the integral mean equation
integral_mean_equation = @(x) ...
    project_function(x, n_inner) - integral_mean_value;

initial_left_value = ...
    integral_mean_equation(initial_left);

initial_right_value = ...
    integral_mean_equation(initial_right);

if initial_left_value * initial_right_value >= 0
    error('The imported interval does not contain a sign change.');
end

fprintf('Initial sign-change test: PASSED\n\n');

%% Solve the equation using the validated bisection method
[integral_mean_point, equation_value, ...
 final_left, final_right, ...
 iteration_count, history_table] = ...
    bisection_method( ...
        integral_mean_equation, ...
        initial_left, ...
        initial_right, ...
        x_tolerance, ...
        maximum_iterations ...
    );

%% Evaluate the original project function at the computed point
F_at_integral_mean_point = project_function( ...
    integral_mean_point, ...
    n_inner ...
);

equation_residual = abs( ...
    F_at_integral_mean_point ...
    - integral_mean_value ...
);

final_half_width = ...
    (final_right - final_left) / 2;

final_sign_product = ...
    integral_mean_equation(final_left) ...
    * integral_mean_equation(final_right);

reported_root = round(integral_mean_point, 6);

rounded_left = round(final_left, 6);
rounded_right = round(final_right, 6);

theoretical_iteration_bound = ceil( ...
    log2( ...
        (initial_right - initial_left) ...
        / x_tolerance ...
    ) ...
);

%% Display final results
fprintf('Final numerical results:\n\n');

fprintf('Computed point c_I     = %.15f\n', ...
    integral_mean_point);

fprintf('Rounded c_I (6 digits) = %.6f\n\n', ...
    reported_root);

fprintf('F(c_I)                 = %.15f\n', ...
    F_at_integral_mean_point);

fprintf('Integral mean M_I      = %.15f\n', ...
    integral_mean_value);

fprintf('|F(c_I) - M_I|         = %.15e\n\n', ...
    equation_residual);

fprintf('Equation value G_I(c_I)= %.15e\n', ...
    equation_value);

fprintf('Iteration count        = %d\n', ...
    iteration_count);

fprintf('Theoretical bound      = %d\n\n', ...
    theoretical_iteration_bound);

fprintf('Final bracket:\n');
fprintf('[%.15f, %.15f]\n\n', ...
    final_left, final_right);

fprintf('Final half-width       = %.15e\n', ...
    final_half_width);

fprintf('Final sign product     = %.15e\n\n', ...
    final_sign_product);

%% Display the last iterations
number_of_rows_to_display = min(8, height(history_table));

fprintf('Last %d bisection iterations:\n\n', ...
    number_of_rows_to_display);

disp(history_table( ...
    end - number_of_rows_to_display + 1:end, : ...
));

%% Validate the final result
if final_half_width > x_tolerance
    error('The final bisection interval is not sufficiently small.');
end

fprintf('Final-bracket width test: PASSED\n');

if final_sign_product > 0
    error('The final interval does not preserve the sign change.');
end

fprintf('Sign-change preservation test: PASSED\n');

if integral_mean_point < initial_left || ...
        integral_mean_point > initial_right

    error('The computed point lies outside the initial bracket.');
end

fprintf('Root-location test: PASSED\n');

if equation_residual > 1e-6
    error('The integral mean equation residual is too large.');
end

fprintf('Integral-mean equation test: PASSED\n');

if rounded_left ~= rounded_right
    error(['The final bracket does not produce a stable ', ...
           'six-decimal rounded value.']);
end

fprintf('Six-decimal rounding stability test: PASSED\n');

%% Save the bisection iteration history
history_file_path = fullfile( ...
    results_directory, ...
    'integral_mean_point_bisection_history.csv' ...
);

writetable(history_table, history_file_path);

%% Save the final summary
summary_table = table( ...
    integral_mean_point, ...
    reported_root, ...
    F_at_integral_mean_point, ...
    integral_mean_value, ...
    equation_residual, ...
    final_left, ...
    final_right, ...
    final_half_width, ...
    iteration_count, ...
    'VariableNames', ...
    { ...
        'IntegralMeanPoint', ...
        'RoundedPointSixDecimals', ...
        'FunctionValueAtPoint', ...
        'IntegralMeanValue', ...
        'EquationResidual', ...
        'FinalLeft', ...
        'FinalRight', ...
        'FinalHalfWidth', ...
        'IterationCount' ...
    } ...
);

summary_file_path = fullfile( ...
    results_directory, ...
    'integral_mean_point_summary.csv' ...
);

writetable(summary_table, summary_file_path);

%% Generate the final integral mean theorem plot
x_plot = linspace(a, b, 501);

F_plot = project_function(x_plot, n_inner);

figure_handle = figure('Color', 'w');

plot(x_plot, F_plot, 'LineWidth', 1.5);
hold on;

yline( ...
    integral_mean_value, ...
    '--', ...
    'LineWidth', ...
    1.2 ...
);

plot( ...
    integral_mean_point, ...
    F_at_integral_mean_point, ...
    'o', ...
    'MarkerSize', ...
    8, ...
    'LineWidth', ...
    1.5 ...
);

grid on;

xlabel('x');
ylabel('F(x)');
title('Integral Mean Theorem Point');

legend( ...
    'F(x)', ...
    'Integral mean M_I', ...
    'Integral mean point c_I', ...
    'Location', ...
    'best' ...
);

axes_handle = gca;
axes_handle.Toolbar.Visible = 'off';

figure_file_path = fullfile( ...
    figures_directory, ...
    'integral_mean_theorem_point.png' ...
);

exportgraphics( ...
    figure_handle, ...
    figure_file_path, ...
    'Resolution', ...
    300 ...
);

%% Display saved file paths
fprintf('\nBisection history saved to:\n%s\n', ...
    history_file_path);

fprintf('\nFinal summary saved to:\n%s\n', ...
    summary_file_path);

fprintf('\nFinal figure saved to:\n%s\n', ...
    figure_file_path);

%% Final message
fprintf('\nStep 09 completed successfully.\n');
fprintf('====================================================\n');