%% Step 12: Find brackets for the derivative mean value theorem point
clear;
clc;
format long g;

fprintf('====================================================\n');
fprintf('STEP 12 - DERIVATIVE MEAN VALUE ROOT BRACKETS\n');
fprintf('====================================================\n\n');

%% Project settings
a = 0.0;
b = 1.0;

stencil_size = 5;
number_of_scan_points = 2001;

fprintf('Project interval      : [%.1f, %.1f]\n', a, b);
fprintf('Local stencil size    : %d\n', stencil_size);
fprintf('Number of scan points : %d\n\n', ...
    number_of_scan_points);

%% Determine project folders
script_full_path = mfilename('fullpath');

if isempty(script_full_path)
    error(['The script must be saved before execution so that ', ...
           'the project path can be determined.']);
end

code_directory = fileparts(script_full_path);
project_root = fileparts(code_directory);

results_directory = fullfile(project_root, 'results');
figures_directory = fullfile(project_root, 'figures');

if ~exist(results_directory, 'dir')
    mkdir(results_directory);
end

if ~exist(figures_directory, 'dir')
    mkdir(figures_directory);
end

fprintf('Project root:\n%s\n\n', project_root);

%% Read the fine derivative data from Step 11
derivative_file_path = fullfile( ...
    results_directory, ...
    'project_function_numerical_derivative.csv' ...
);

if ~isfile(derivative_file_path)
    error(['The Step 11 derivative file was not found:\n', ...
           derivative_file_path]);
end

derivative_table = readtable(derivative_file_path);

required_variables = { ...
    'x', ...
    'F_x', ...
    'NumericalDerivative' ...
};

if ~all(ismember( ...
        required_variables, ...
        derivative_table.Properties.VariableNames))

    error(['The Step 11 derivative table does not contain ', ...
           'the required columns.']);
end

x_nodes = derivative_table.x;
F_nodes = derivative_table.F_x;

if any(~isfinite(x_nodes)) || any(~isreal(x_nodes))
    error('The imported x nodes are invalid.');
end

if any(~isfinite(F_nodes)) || any(~isreal(F_nodes))
    error('The imported function values are invalid.');
end

if any(diff(x_nodes) <= 0)
    error('The imported x nodes must be strictly increasing.');
end

if abs(x_nodes(1) - a) > 1e-12 || ...
        abs(x_nodes(end) - b) > 1e-12

    error('The imported numerical table does not cover [0, 1].');
end

fprintf('Step 11 derivative data imported successfully.\n\n');

%% Compute the average slope
F_left_endpoint = F_nodes(1);
F_right_endpoint = F_nodes(end);

average_slope = ...
    (F_right_endpoint - F_left_endpoint) ...
    / (b - a);

fprintf('Endpoint function values:\n');
fprintf('F(0) = %.15f\n', F_left_endpoint);
fprintf('F(1) = %.15f\n\n', F_right_endpoint);

fprintf('Average slope:\n');
fprintf('M_D = (F(1) - F(0)) / (1 - 0)\n');
fprintf('M_D = %.15f\n\n', average_slope);

%% Construct a fine scan grid
x_scan = linspace( ...
    a, ...
    b, ...
    number_of_scan_points ...
).';

scan_spacing = x_scan(2) - x_scan(1);

%% Evaluate the numerical derivative on the scan grid
[~, derivative_scan] = local_newton_interpolant( ...
    x_nodes, ...
    F_nodes, ...
    x_scan, ...
    stencil_size ...
);

if any(~isfinite(derivative_scan)) || ...
        any(~isreal(derivative_scan))

    error('The derivative scan contains invalid values.');
end

fprintf('Scan spacing: %.15f\n', scan_spacing);
fprintf('Finite real derivative scan test: PASSED\n\n');

%% Define the derivative mean value equation
G_derivative_scan = ...
    derivative_scan - average_slope;

%% Check that the average slope is inside the derivative range
minimum_derivative = min(derivative_scan);
maximum_derivative = max(derivative_scan);

fprintf('Numerical derivative range:\n');
fprintf('Minimum derivative = %.15f\n', minimum_derivative);
fprintf('Maximum derivative = %.15f\n\n', maximum_derivative);

if average_slope < minimum_derivative || ...
        average_slope > maximum_derivative

    error(['The average slope is outside the numerical ', ...
           'derivative range.']);
end

fprintf('Average-slope range test: PASSED\n\n');

%% Locate all sign-change brackets
sign_change_indices = find( ...
    G_derivative_scan(1:end-1) ...
    .* G_derivative_scan(2:end) < 0 ...
);

number_of_brackets = numel(sign_change_indices);

if number_of_brackets == 0
    error(['No sign-change bracket was detected for ', ...
           'the derivative mean value equation.']);
end

bracket_number = (1:number_of_brackets).';

x_left = x_scan(sign_change_indices);
x_right = x_scan(sign_change_indices + 1);

derivative_left = derivative_scan(sign_change_indices);
derivative_right = derivative_scan(sign_change_indices + 1);

G_left = G_derivative_scan(sign_change_indices);
G_right = G_derivative_scan(sign_change_indices + 1);

bracket_width = x_right - x_left;

bracket_table = table( ...
    bracket_number, ...
    x_left, ...
    x_right, ...
    derivative_left, ...
    derivative_right, ...
    G_left, ...
    G_right, ...
    bracket_width, ...
    'VariableNames', ...
    { ...
        'BracketNumber', ...
        'x_left', ...
        'x_right', ...
        'DerivativeLeft', ...
        'DerivativeRight', ...
        'G_left', ...
        'G_right', ...
        'BracketWidth' ...
    } ...
);

fprintf('Number of sign-change brackets: %d\n\n', ...
    number_of_brackets);

fprintf('Detected derivative-mean brackets:\n\n');
disp(bracket_table);

%% Validate the brackets
bracket_products = G_left .* G_right;

if any(bracket_products >= 0)
    error('At least one detected interval is not a valid bracket.');
end

fprintf('Sign-change validation test: PASSED\n');

%% Construct and save the complete scan table
scan_table = table( ...
    x_scan, ...
    derivative_scan, ...
    G_derivative_scan, ...
    'VariableNames', ...
    { ...
        'x', ...
        'NumericalDerivative', ...
        'DerivativeMeanEquation' ...
    } ...
);

scan_file_path = fullfile( ...
    results_directory, ...
    'derivative_mean_value_root_scan.csv' ...
);

writetable(scan_table, scan_file_path);

%% Save the bracket table
bracket_file_path = fullfile( ...
    results_directory, ...
    'derivative_mean_value_root_brackets.csv' ...
);

writetable(bracket_table, bracket_file_path);

%% Save the average-slope summary
average_slope_table = table( ...
    F_left_endpoint, ...
    F_right_endpoint, ...
    average_slope, ...
    minimum_derivative, ...
    maximum_derivative, ...
    'VariableNames', ...
    { ...
        'F_0', ...
        'F_1', ...
        'AverageSlope', ...
        'MinimumNumericalDerivative', ...
        'MaximumNumericalDerivative' ...
    } ...
);

average_slope_file_path = fullfile( ...
    results_directory, ...
    'derivative_mean_value_slope_summary.csv' ...
);

writetable(average_slope_table, average_slope_file_path);

%% Plot the derivative and average slope
figure_handle = figure('Color', 'w');

plot( ...
    x_scan, ...
    derivative_scan, ...
    'LineWidth', ...
    1.5 ...
);

hold on;

yline( ...
    average_slope, ...
    '--', ...
    'LineWidth', ...
    1.2 ...
);

plot( ...
    x_left, ...
    derivative_left, ...
    'o', ...
    'MarkerSize', ...
    7, ...
    'LineWidth', ...
    1.3 ...
);

plot( ...
    x_right, ...
    derivative_right, ...
    'o', ...
    'MarkerSize', ...
    7, ...
    'LineWidth', ...
    1.3 ...
);

grid on;

xlabel('x');
ylabel('Numerical approximation of F''(x)');

title( ...
    'Derivative Mean Value Equation and Sign-Change Bracket' ...
);

legend( ...
    'Numerical derivative', ...
    'Average slope', ...
    'Left bracket endpoint', ...
    'Right bracket endpoint', ...
    'Location', ...
    'best' ...
);

axes_handle = gca;
axes_handle.Toolbar.Visible = 'off';

figure_file_path = fullfile( ...
    figures_directory, ...
    'derivative_mean_value_bracket_scan.png' ...
);

exportgraphics( ...
    figure_handle, ...
    figure_file_path, ...
    'Resolution', ...
    300 ...
);

%% Display saved paths
fprintf('\nComplete scan table saved to:\n%s\n', ...
    scan_file_path);

fprintf('\nBracket table saved to:\n%s\n', ...
    bracket_file_path);

fprintf('\nAverage-slope summary saved to:\n%s\n', ...
    average_slope_file_path);

fprintf('\nFigure saved to:\n%s\n', ...
    figure_file_path);

%% Final message
fprintf('\nStep 12 completed successfully.\n');
fprintf('====================================================\n');