%% Step 13: Compute the derivative mean value theorem point
clear;
clc;
format long g;

fprintf('====================================================\n');
fprintf('STEP 13 - DERIVATIVE MEAN VALUE THEOREM POINT\n');
fprintf('====================================================\n\n');

%% Project settings
a = 0.0;
b = 1.0;

stencil_size = 5;

% A strict tolerance stabilizes six-decimal rounding.
x_tolerance = 0.5e-8;
maximum_iterations = 100;

fprintf('Project interval      : [%.1f, %.1f]\n', a, b);
fprintf('Local stencil size    : %d\n', stencil_size);
fprintf('Bisection tolerance   : %.10e\n', x_tolerance);
fprintf('Maximum iterations    : %d\n\n', maximum_iterations);

%% Determine project folders
script_full_path = mfilename('fullpath');

if isempty(script_full_path)
    error(['The script must be saved before execution so that ', ...
           'the project path can be determined.']);
end

code_directory = fileparts(script_full_path);
project_root = fileparts(code_directory);

results_directory = fullfile(project_root, 'results');
figures_directory = fullfile(project_root, 'figures');

if ~exist(results_directory, 'dir')
    mkdir(results_directory);
end

if ~exist(figures_directory, 'dir')
    mkdir(figures_directory);
end

fprintf('Project root:\n%s\n\n', project_root);

%% Read the numerical function data from Step 11
derivative_data_path = fullfile( ...
    results_directory, ...
    'project_function_numerical_derivative.csv' ...
);

if ~isfile(derivative_data_path)
    error(['The Step 11 derivative data file was not found:\n', ...
           derivative_data_path]);
end

derivative_data_table = readtable(derivative_data_path);

required_data_variables = {'x', 'F_x'};

if ~all(ismember( ...
        required_data_variables, ...
        derivative_data_table.Properties.VariableNames))

    error(['The Step 11 table does not contain the required ', ...
           'x and F_x columns.']);
end

x_nodes = derivative_data_table.x;
F_nodes = derivative_data_table.F_x;

if any(~isfinite(x_nodes)) || any(~isreal(x_nodes))
    error('The imported interpolation nodes are invalid.');
end

if any(~isfinite(F_nodes)) || any(~isreal(F_nodes))
    error('The imported project function values are invalid.');
end

if any(diff(x_nodes) <= 0)
    error('The imported interpolation nodes must be increasing.');
end

fprintf('Step 11 numerical function data imported successfully.\n');

%% Read the average slope from Step 12
slope_summary_path = fullfile( ...
    results_directory, ...
    'derivative_mean_value_slope_summary.csv' ...
);

if ~isfile(slope_summary_path)
    error(['The Step 12 average-slope file was not found:\n', ...
           slope_summary_path]);
end

slope_summary_table = readtable(slope_summary_path);

if ~ismember( ...
        'AverageSlope', ...
        slope_summary_table.Properties.VariableNames)

    error('The Step 12 file does not contain AverageSlope.');
end

average_slope = slope_summary_table.AverageSlope(1);

if ~isscalar(average_slope) || ...
        ~isreal(average_slope) || ...
        ~isfinite(average_slope)

    error('The imported average slope is invalid.');
end

fprintf('Average slope imported successfully:\n');
fprintf('M_D = %.15f\n\n', average_slope);

%% Read the initial sign-change bracket from Step 12
bracket_file_path = fullfile( ...
    results_directory, ...
    'derivative_mean_value_root_brackets.csv' ...
);

if ~isfile(bracket_file_path)
    error(['The Step 12 bracket file was not found:\n', ...
           bracket_file_path]);
end

bracket_table = readtable(bracket_file_path);

required_bracket_variables = {'x_left', 'x_right'};

if ~all(ismember( ...
        required_bracket_variables, ...
        bracket_table.Properties.VariableNames))

    error('The Step 12 bracket file has invalid columns.');
end

if height(bracket_table) ~= 1
    error(['Exactly one derivative-mean bracket was expected, ', ...
           'but %d brackets were found.'], ...
           height(bracket_table));
end

initial_left = bracket_table.x_left(1);
initial_right = bracket_table.x_right(1);

fprintf('Initial root bracket:\n');
fprintf('[%.15f, %.15f]\n\n', ...
    initial_left, initial_right);

%% Define the numerical derivative function
numerical_derivative = @(x) ...
    project_derivative_approximation( ...
        x_nodes, ...
        F_nodes, ...
        x, ...
        stencil_size ...
    );

%% Define the derivative mean value equation
derivative_mean_equation = @(x) ...
    numerical_derivative(x) - average_slope;

initial_left_value = ...
    derivative_mean_equation(initial_left);

initial_right_value = ...
    derivative_mean_equation(initial_right);

fprintf('Equation values at initial endpoints:\n');
fprintf('G_D(left)  = %.15e\n', initial_left_value);
fprintf('G_D(right) = %.15e\n\n', initial_right_value);

if initial_left_value * initial_right_value >= 0
    error('The imported interval does not contain a sign change.');
end

fprintf('Initial sign-change test: PASSED\n\n');

%% Solve with the validated bisection method
[derivative_mean_point, equation_value, ...
 final_left, final_right, ...
 iteration_count, history_table] = ...
    bisection_method( ...
        derivative_mean_equation, ...
        initial_left, ...
        initial_right, ...
        x_tolerance, ...
        maximum_iterations ...
    );

%% Evaluate and validate the final result
derivative_at_point = numerical_derivative( ...
    derivative_mean_point ...
);

equation_residual = abs( ...
    derivative_at_point - average_slope ...
);

final_half_width = ...
    (final_right - final_left) / 2;

final_sign_product = ...
    derivative_mean_equation(final_left) ...
    * derivative_mean_equation(final_right);

reported_point = round(derivative_mean_point, 6);

rounded_left = round(final_left, 6);
rounded_right = round(final_right, 6);

theoretical_iteration_bound = ceil( ...
    log2( ...
        (initial_right - initial_left) ...
        / x_tolerance ...
    ) ...
);

%% Display final numerical results
fprintf('Final numerical results:\n\n');

fprintf('Computed point c_D     = %.15f\n', ...
    derivative_mean_point);

fprintf('Rounded c_D (6 digits) = %.6f\n\n', ...
    reported_point);

fprintf('Numerical F''(c_D)      = %.15f\n', ...
    derivative_at_point);

fprintf('Average slope M_D      = %.15f\n', ...
    average_slope);

fprintf('|F''(c_D) - M_D|        = %.15e\n\n', ...
    equation_residual);

fprintf('Equation value G_D(c_D)= %.15e\n', ...
    equation_value);

fprintf('Iteration count        = %d\n', ...
    iteration_count);

fprintf('Theoretical bound      = %d\n\n', ...
    theoretical_iteration_bound);

fprintf('Final bracket:\n');
fprintf('[%.15f, %.15f]\n\n', ...
    final_left, final_right);

fprintf('Final half-width       = %.15e\n', ...
    final_half_width);

fprintf('Final sign product     = %.15e\n\n', ...
    final_sign_product);

%% Display the last iterations
number_of_rows_to_display = min(8, height(history_table));

fprintf('Last %d bisection iterations:\n\n', ...
    number_of_rows_to_display);

disp(history_table( ...
    end - number_of_rows_to_display + 1:end, : ...
));

%% Final validation tests
if final_half_width > x_tolerance
    error('The final bisection interval is not sufficiently small.');
end

fprintf('Final-bracket width test: PASSED\n');

if final_sign_product > 0
    error('The final interval does not preserve the sign change.');
end

fprintf('Sign-change preservation test: PASSED\n');

if derivative_mean_point < initial_left || ...
        derivative_mean_point > initial_right

    error('The computed point lies outside the initial bracket.');
end

fprintf('Root-location test: PASSED\n');

if equation_residual > 1e-6
    error('The derivative mean value residual is too large.');
end

fprintf('Derivative-mean equation test: PASSED\n');

if rounded_left ~= rounded_right
    error(['The final bracket does not produce a stable ', ...
           'six-decimal rounded value.']);
end

fprintf('Six-decimal rounding stability test: PASSED\n');

%% Save the iteration history
history_file_path = fullfile( ...
    results_directory, ...
    'derivative_mean_point_bisection_history.csv' ...
);

writetable(history_table, history_file_path);

%% Save the final summary
summary_table = table( ...
    derivative_mean_point, ...
    reported_point, ...
    derivative_at_point, ...
    average_slope, ...
    equation_residual, ...
    final_left, ...
    final_right, ...
    final_half_width, ...
    iteration_count, ...
    'VariableNames', ...
    { ...
        'DerivativeMeanPoint', ...
        'RoundedPointSixDecimals', ...
        'NumericalDerivativeAtPoint', ...
        'AverageSlope', ...
        'EquationResidual', ...
        'FinalLeft', ...
        'FinalRight', ...
        'FinalHalfWidth', ...
        'IterationCount' ...
    } ...
);

summary_file_path = fullfile( ...
    results_directory, ...
    'derivative_mean_point_summary.csv' ...
);

writetable(summary_table, summary_file_path);

%% Generate the final theorem plot
x_plot = linspace(a, b, 1001);

derivative_plot = numerical_derivative(x_plot);

figure_handle = figure('Color', 'w');

plot( ...
    x_plot, ...
    derivative_plot, ...
    'LineWidth', ...
    1.5 ...
);

hold on;

yline( ...
    average_slope, ...
    '--', ...
    'LineWidth', ...
    1.2 ...
);

plot( ...
    derivative_mean_point, ...
    derivative_at_point, ...
    'o', ...
    'MarkerSize', ...
    8, ...
    'LineWidth', ...
    1.5 ...
);

grid on;

xlabel('x');
ylabel('Numerical approximation of F''(x)');

title('Derivative Mean Value Theorem Point');

legend( ...
    'Numerical derivative', ...
    'Average slope M_D', ...
    'Derivative mean point c_D', ...
    'Location', ...
    'best' ...
);

axes_handle = gca;
axes_handle.Toolbar.Visible = 'off';

figure_file_path = fullfile( ...
    figures_directory, ...
    'derivative_mean_theorem_point.png' ...
);

exportgraphics( ...
    figure_handle, ...
    figure_file_path, ...
    'Resolution', ...
    300 ...
);

%% Display saved paths
fprintf('\nBisection history saved to:\n%s\n', ...
    history_file_path);

fprintf('\nFinal summary saved to:\n%s\n', ...
    summary_file_path);

fprintf('\nFinal figure saved to:\n%s\n', ...
    figure_file_path);

%% Final message
fprintf('\nStep 13 completed successfully.\n');
fprintf('====================================================\n');